kind: pipeline
type: docker
name: build-runner-base-empty

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/docker
  environment:
    HF_TOKEN:
      from_secret: HF_TOKEN
  pull: always
  settings:
    dockerfile: Dockerfile.runner
    tags:
    - "${DRONE_TAG:-main}-empty" # Default to branch
    - "latest-empty"
    daemon_off: true
    registry: registry.helix.ml
    repo: registry.helix.ml/helix/runner-base
    username: admin
    password:
      from_secret: helix_registry_password
    secret: id=HF_TOKEN,env=HF_TOKEN
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

---
kind: pipeline
type: docker
name: build-runner-base-small

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/docker
  environment:
    HF_TOKEN:
      from_secret: HF_TOKEN
  pull: always
  settings:
    dockerfile: Dockerfile.runner
    tags:
    - "${DRONE_TAG:-main}-small" # Default to branch
    - "latest-small"
    daemon_off: true
    registry: registry.helix.ml
    repo: registry.helix.ml/helix/runner-base
    build_args:
      # Small models only
      - PULL_OLLAMA_MODELS=llama3.1:8b-instruct-q8_0
    secret: id=HF_TOKEN,env=HF_TOKEN
    username: admin
    password:
      from_secret: helix_registry_password
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- build-runner-base-empty

---
kind: pipeline
type: docker
name: build-runner-base-large

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/docker
  environment:
    HF_TOKEN:
      from_secret: HF_TOKEN
  pull: always
  settings:
    dockerfile: Dockerfile.runner
    tags:
    - "${DRONE_TAG:-main}-large"
    - "latest-large"
    daemon_off: true
    registry: registry.helix.ml
    repo: registry.helix.ml/helix/runner-base
    build_args:
      # We put models we're confident in keeping around for a long time in a
      # big base layer, and have a smaller layers on top for models that might
      # change more frequently and that we can add to without churning the
      # 100GB base
      - PULL_OLLAMA_MODELS=llama3.1:8b-instruct-q8_0;llama3.3:70b-instruct-q4_K_M;llama3.2:1b-instruct-q8_0;llama3.2:3b-instruct-q8_0
      - PULL_OLLAMA_MODELS_PHASE_2=phi3.5:3.8b-mini-instruct-q8_0
      - PULL_OLLAMA_MODELS_PHASE_3=qwen2.5:7b-instruct-q8_0
      - PULL_OLLAMA_MODELS_PHASE_4=aya:8b-23-q8_0;aya:35b-23-q4_0
      # disabled for now because not better than flux and trying to minimize disk usage
      # - PULL_DIFFUSERS_MODELS_STABLEDIFFUSION=true
      - PULL_DIFFUSERS_MODELS_FLUX=true
    secret: id=HF_TOKEN,env=HF_TOKEN
    username: admin
    password:
      from_secret: helix_registry_password
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- build-runner-base-small
