kind: pipeline
type: docker
name: build-runner-base-empty

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/docker
  pull: always
  settings:
    dockerfile: Dockerfile.runner
    tags:
    - "${DRONE_TAG:-main}-empty" # Default to branch
    - "latest-empty"
    daemon_off: true
    registry: registry.helix.ml
    repo: registry.helix.ml/helix/runner-base
    username: admin
    password:
      from_secret: helix_registry_password
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

---
kind: pipeline
type: docker
name: build-runner-base-small

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/docker
  pull: always
  settings:
    dockerfile: Dockerfile.runner
    tags:
    - "${DRONE_TAG:-main}-small" # Default to branch
    - "latest-small"
    daemon_off: true
    registry: registry.helix.ml
    repo: registry.helix.ml/helix/runner-base
    build_args:
      # Small models only
      - PULL_OLLAMA_MODELS=llama3:instruct;phi3:instruct;llama3.1:8b;llama3.2:1b;llama3.2:3b;phi3.5:3.8b
    username: admin
    password:
      from_secret: helix_registry_password
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- build-runner-base-empty

---
kind: pipeline
type: docker
name: build-runner-base-large

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/docker
  pull: always
  settings:
    dockerfile: Dockerfile.runner
    tags:
    - "${DRONE_TAG:-main}-large"
    - "latest-large"
    daemon_off: true
    registry: registry.helix.ml
    repo: registry.helix.ml/helix/runner-base
    build_args:
      # We put models we're confident in keeping around for a long time in a
      # big base layer, and have a smaller layer on top for models that might
      # change more frequently and that we can add to without churning the
      # 100GB base
      - PULL_OLLAMA_MODELS=llama3:instruct;phi3:instruct;llama3.1:8b;llama3.2:1b;llama3.2:3b;phi3.5:3.8b;llama3:70b;mixtral:instruct;llama3.1:70b;qwen2.5:7b;qwen2.5:72b
      - PULL_OLLAMA_MODELS_PHASE_2=adrienbrault/nous-hermes2theta-llama3-8b:q8_0;aya:8b;aya:35b
    username: admin
    password:
      from_secret: helix_registry_password
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- build-runner-base-small
